### ISSUE TITLE
Java problem code

### ISSUE THREAD

**Issue by 19733** [matafokka/ezforum#1]
i am having a problem with my java code infortunoly, my code are not working after certain point, after reading the operacao value, the code simply stops. Can someone help me?

There is my code:

import java.util.Scanner;
public class Main
{
	public static void main(String[] args) {
	  Scanner ler = new Scanner(System.in);
	  //habilitando função ler
	  float a,b;
	  float soma,subtracao,multiplicacao,divisao;
	  String operacao;
	  //declarando variaveis
	  System.out.println("insira um valor para A: ");
	    a = ler.nextFloat();
	  //escreva e leia valor de A 
	  System.out.println("Digite a operação matemática que deseja realizar: +,-,x ou /: ");
	    operacao = ler.next();
	  //escreva e leia valor da operação
	  while(operacao != "+" && operacao != "-" && operacao != "x" && operacao != "/");{
	      if (operacao != "+" && operacao != "-" && operacao != "x" && operacao != "/");{
	          System.out.println("Operação inválida, digite +,-,x ou / para as operações matemáticas: ");
	            operacao = ler.next();
	            //enquanto operação <> "+","-","x" e "/" escreva "Operação inválida, digite +,-,x ou / para as operações matemáticas:" e leia operação
	      }
	  }
	  System.out.println("Insira um valor para B: ");
        b = ler.nextFloat();
	    // escreva e leia valor de B
	    soma = a+b;
        subtracao = a-b;
        multiplicacao = a*b;
        divisao = a/b;
        // atribuindo valores as expreções matemáticas
        if (operacao == "+"){
            System.out.println(a+ " +"+b+" é igual a"+soma);
            // se valor de operação = "+" então operação de soma
        }
        if (operacao == "-"){
            System.out.println(a+" -"+b+" é igual a"+subtracao);
            // se valor de operação = "-" então operação de subtração
        }
        if(operacao == "x"){
            System.out.println(a+" x"+b+" é igual a"+multiplicacao);
             // se valor de operação = "x" então operação de multiplicação
        }
        if (operacao == "/"){
            System.out.println(a+" /"+b+" é igual a"+divisao);
            // se valor de operação = "/" então operação de divisão
            
        }
	}
}

[import java.docx](https://github.com/Erudika/scoold/files/8481255/import.java.docx)

**Comment by matafokka** [comment]
Hello, before I answer your question, I have a few things to point out:

1. GitHub is for publishing projects, not for programming-related questions. For that, use StackOverflow.
2. Always format the code, it's unreadable in plain text.
3. Try to figure out the issue yourself first, then ask the question. The solution is very simple in your case. Later, you'll encounter problems much harder than this one, so learn to analyze now.

Now to your problem.

First, in `while` loop there's redundant semicolon. It makes your loop have no body, so it'll run infinitely.

Second, in Java, **never** compare strings with `==` operator. Strings are objects, not primitives, so you need to compare them using `equals()` method. If `==` is used on objects, Java will check if pointers to those objects match.

Third, since strings are objects, you need to initialize them before calling any of their methods. Otherwise, you'll get `NullPointerException`. You can assign strings to an empty string using special syntax like so: `string myString = ""`.  For other objects, call their constructor like so: `Object myObj = new Object();`. Your professor will explain all of it when you'll get to OOP.

I also have some notes on your code not related to the question:

1. Write your comments, variables, etc in English. Who knows who might read your code? Also, English reads way better since every keyword in almost every programming language is an English word.
2. Remove `if` in `while` loop. It's the same condition, you don't need to duplicate it.
5. See last four conditions? They do the same thing, only variables differ. You need to generalize it, you're using a computer after all, make it do the work for you.
6. Declare variables where you first assign them (except some cases when you need `null` value initially). It's just better style.

Here's your refactored and working code:

```java
import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        Scanner ler = new Scanner(System.in);
        
        System.out.println("a: ");
        float a = ler.nextFloat();
        
        String operation = "";
        while (!(operation.equals("+") || operation.equals("-") || operation.equals("/") || operation.equals("x"))) {
            System.out.println("Operation: ");
            operation = ler.next();
        }
        
        System.out.println("b: ");
        float b = ler.nextFloat();
        
        float result;
        switch (operation) {
            case "+":
                result = a + b;
                break;
            case "-":
                result = a - b;
                break;
            case "/":
                result = a / b;
                break;
            default:
                result = a * b;
                break;
        }
        
        System.out.println(a + operation + b + " = " + result);
    }
}
```

**Comment by albogdano** [comment]
@matafokka That guy also spams other projects with the same issue. Don't bother helping him.

**Comment by albogdano** [comment]
You are too kind, but it seems to me we're dealing with a spammer. I already reported him.

**Comment by matafokka** [comment]
Thank you :3

Yeah, I'll report him too then. Let the admins deal with it.

**Comment by 19733** [comment]
Partners i am new in Github plataform and programation, sorry for bother them, i just did not knew how the things works here
